### PR TITLE
Update main.yml

### PR DESCRIPTION
**Pull request by prnjl117**

### CODE REVIEW

**Comment by 4z4r43l-private** [comment]
pr comment

**Comment by prnjl117** [comment]
new comment

**Comment by prnjl117** [comment]
new comment 2

**Comment by prnjl117** [comment]
comment 3

**Comment by 4z4r43l-private** [comment]
ssk commet

**Comment by 4z4r43l-private** [comment]
sdfr

**Comment by 4z4r43l-private** [comment]
cvnb

**Comment by prnjl117** [comment]
add comment

**Comment by prnjl117** [comment]
new commnt

**Pull request closed without merging**
